# Theme
remote_theme: 'epidrome/cover-card'

# Title and tag line
title: 'Stephanie M. Wyatt'
description: "Rev. Dr. Stephanie Wyatt earned her Ph.D. in the area of Hebrew Bible (Old Testament) from Brite Divinity School in Ft Worth, TX."

# Images
avatar: 'static/assets/images/stephaniewyatt.jpg'
background: 'static/assets/images/background.png'
favicon: 'static/assets/images/favicon/favicon.ico'

# Online profiles
website: 'stephaniewyatt.net'
linkedin: 'stephaniewyatt'
academia: 'tcu.academia.edu/StephanieWyatt'
orcid: 'orcid.org/0000-0002-4472-5316'
google_scholar: 'scholar.google.com/citations?user=43gFBr8AAAAJ'
email: 'stephanie@stephaniewyatt.net'
#instagram: '__USERNAME__'
#blog_url: '__USERNAME__'
#github-user: '__USERNAME__'
#twitter: '__USERNAME__'
#dribbble: '__USERNAME__'
#facebook: '__USERNAME__'
#gitlab-user: '__USERNAME__'
#codepen: '__USERNAME__'
#pinterest: '__USERNAME__'
#youtube: '__USERNAME__'
#steam: '__USERNAME__'
#soundcloud: '__USERNAME__'
#lastfm: '__USERNAME__'
#stack-overflow: '__USERNAME__'
#reddit: '__USERNAME__'
#medium:  '__USERNAME__'
#tumblr: '__USERNAME__'
#weibo: '__USERNAME__'
#vk: '__USERNAME__'
#messenger: '__USERNAME__'

social-links-order: [website, inkedin, academia, orcid, google_scholar, email]

# Advanced settings
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

# Yaml manifest of supported social links
# Requirements:
# `name`
#     - plain-text name of the site (e.g. twitter)
#     - **mandatory**
# `url-pattern`
#     - site URL pattern containing a placeholder string (e.g. twitter.com/__USERNAME__)
#     - placeholder will be replaced by username or value specified in _config.yml (e.g. twitter.com/mytwitter)
#     - **mandatory**
# `url-scheme`
#     - the hardcoded URI/URN url-scheme (e.g. https://)
#     - can be one of: ['https://', 'http://', 'mailto:']
#     - defaults to '//'
#     - **optional**
# `icon-class`
#     - the font awesome icon class names
#     - font-awesome free and supports `fas` (solid) and `fab` (brands) styles
#     - defaults to `fab` style and uses value of `name` attribute (e.g. fab fa-2x fa-twitter)
#     - **optional**
social-links:
  - name: facebook
    url-pattern: facebook.com/__USERNAME__
    icon-class: fab fa-2x fa-facebook-f

  - name: twitter
    url-pattern: twitter.com/__USERNAME__

  - name: linkedin
    url-pattern: linkedin.com/in/__USERNAME__

  - name: google-plus
    url-pattern: plus.google.com/+__USERNAME__

  - name: vk
    url-pattern: vk.com/__USERNAME__

  - name: weibo
    url-pattern: weibo.com/__USERNAME__

  - name: instagram
    url-pattern: instagram.com/__USERNAME__

  - name: flickr
    url-pattern: flickr.com/__USERNAME__

  - name: pinterest
    url-pattern: pinterest.com/__USERNAME__

  - name: github-user
    url-pattern: github.com/__USERNAME__
    icon-class: fab fa-2x fa-github

  - name: gitlab-user
    url-pattern: gitlab.com/__USERNAME__
    icon-class: fab fa-2x fa-gitlab

  - name: codepen
    url-pattern: codepen.com/__USERNAME__

  - name: stack-overflow
    url-pattern: stackoverflow.com/users/__USERNAME__

  - name: reddit
    url-pattern: reddit.com/user/__USERNAME__

  - name: steam
    url-pattern: steamcommunity.com/id/__USERNAME__

  - name: youtube
    url-pattern: youtube.com/__USERNAME__

  - name: vimeo
    url-pattern: vimeo.com/__USERNAME__

  - name: soundcloud
    url-pattern: soundcloud.com/__USERNAME__

  - name: lastfm
    url-pattern: last.fm/user/__USERNAME__

  - name: medium
    url-pattern: medium.com/@__USERNAME__

  - name: tumblr
    url-pattern: __USERNAME__.tumblr.com

  - name: dribbble
    url-pattern: dribbble.com/__USERNAME__

  - name: keybase
    url-pattern: keybase.io/__USERNAME__

  - name: messenger
    url-pattern: m.me/__USERNAME__
    icon-class: fab fa-2x fa-facebook-messenger

  - name: telegram
    url-pattern: telegram.me/__USERNAME__

  - name: snapchat
    url-pattern: snapchat.com/add/__USERNAME__

  - name: quora
    url-pattern: www.quora.com/profile/__USERNAME__

  - name: blog_url
    url-pattern: '__USERNAME__'
    icon-class: fas fa-2x fa-tags

  - name: website
    url-pattern: '__USERNAME__'
    icon-class: fas fa-2x fa-globe

  - name: academia
    url-pattern: '__USERNAME__'
    icon-class: fas fa-2x fa-university

  - name: orcid
    url-pattern: '__USERNAME__'
    icon-class: fas fa-2x fa-id-badge

  - name: google_scholar
    url-pattern: '__USERNAME__'
    icon-class: fab fa-2x fa-google

  - name: email
    url-scheme: 'mailto:'
    url-pattern: '__USERNAME__'
    icon-class: fas fa-2x fa-envelope
